local GV = loadstring(readfile("GUIWorkspace/init.lua"))()
local s = GV.SelfFX.new({ flags = {} }) -- servicios reales (camara real)
s:Set("Local_Enabled", true); s:Set("Local_Crosshair", true); s:Set("Local_CrosshairStyle", "Cross")
s:Set("Local_CrosshairSize", 10); s:Set("Local_CrosshairGap", 4)
s:Set("Local_CrosshairColor", Color3.fromRGB(0, 255, 0))
s:_update()
print("[TEST] crosshair Cross lineas -> " .. ((s._cross and s._cross.top.Visible and s._cross.left.Visible) and "PASS" or "FAIL"))
s:Set("Local_CrosshairStyle", "Dot"); s:_update()
print("[TEST] crosshair Dot -> " .. ((s._cross and s._cross.dot.Visible and not s._cross.top.Visible) and "PASS" or "FAIL"))
s:Set("Local_CrosshairStyle", "Circle"); s:_update()
print("[TEST] crosshair Circle -> " .. ((s._cross and s._cross.circle.Visible) and "PASS" or "FAIL"))
-- watermark
s:Set("Local_Watermark", true); s:_update()
print("[TEST] watermark text -> " .. ((s._hud and s._hud.wm.Visible and #s._hud.wm.Text > 0) and "PASS" or "FAIL"))
s:Unload()
-- hitmarker via BindableEvent como hitSignal
local be = Instance.new("BindableEvent")
local s2 = GV.SelfFX.new({ flags = {}, provider = { hitSignal = be.Event } })
s2:Set("Local_Enabled", true); s2:Set("Local_Hitmarker", true)
s2:Init()
be:Fire(); task.wait(0.05)
print("[TEST] hitmarker active tras fire -> " .. ((s2._hitUntil and tick() < s2._hitUntil) and "PASS" or "FAIL"))
s2:_update()
print("[TEST] hitmarker linea visible -> " .. ((s2._hud and s2._hud.hit[1].Visible) and "PASS" or "FAIL"))
s2:Unload(); be:Destroy()
print("[TEST] demo_selffx DONE")
